name = "smartfinance-ai"
main = "workers/ai-service.ts"
compatibility_date = "2024-03-19"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "financial-data"

[[kv_namespaces]]
binding = "FINANCIAL_DATA"
preview_id = "124ebe2525a745eea82914f84a4414f3"
id = "124ebe2525a745eea82914f84a4414f3" 
API_KEY = ""

[vars]
API_KEY = ""